### ISSUE TITLE
Construir script de upgrade de contrato a v1.2.0

### ISSUE THREAD

**Issue by cmauriciocoronel** [ACDI-Argentina/efem-crowdfunding-dapp#17]
En base a las instrucciones de actualización del contrato v1.1.0, se requiere construir una rutina análoga para la versión 1.2.0.

Referencia:
- Instrucciones: https://github.com/ACDI-Argentina/efem-aragon-apps/tree/master/apps/crowdfunding#v110
- Script: https://github.com/ACDI-Argentina/efem-aragon-apps/blob/master/apps/crowdfunding/scripts/upgrade-v1.1.0.js

NOTA: en la v1.1.0 particularmente no se reemplaza el contrato base de crowdfunding. Tener en cuenta el script de actualización genérico del contrato: https://github.com/ACDI-Argentina/efem-aragon-apps/blob/master/apps/crowdfunding/scripts/upgrade.js.

**Comment by ebanchio** [comment]
Script construido y ejecutado en testing y producción.
