### ISSUE TITLE
Actualizar certificado SSL de https://beta.give4forest.org

### ISSUE THREAD

**Issue by cmauriciocoronel** [ACDI-Argentina/efem-crowdfunding-dapp#22]
El certificado SSL del dominio https://beta.give4forest.org está vencido.

Se requiere actualizar el certificado.

NOTA: Me fijé en la configuración de Digital Ocean y no está definido allí el dominio.

**Comment by cmauriciocoronel** [comment]
@jonduttweiler, si sabes decime dónde está configurado dicho dominio así lo puedo actualizar yo. Gracias.

**Comment by jonduttweiler** [comment]
Mauri, la configuración de los certificados se hace con certbot conectandote al servidor por ssh.
``certbot renew --cert-name beta.give4forest.org``

También podes ver los certificados disponibles y la fecha de expiración de cada uno con ``certbot certificates`` . Creería que se tienen que renovar solos, pero al correr el comando me dio problemas con el subdomain feathers.beta.give4forest.org. Temporalmente saqué este del certificado, y lo pude renovar. No se si este subdomain está siendo usado, pero decime y cualquier cosa lo vemos.

**Comment by cmauriciocoronel** [comment]
Muchas gracias @jonduttweiler.

El dominio `feathers.beta.give4forest.org` no lo usamos porque Give4Forest no tiene servicios de Feathers específicos.

Por otra parte, me está fallando la autenticación para acceder por SSH a la VM de efem-testing; hace 3 días funcionaba. Cambiaste la password del usuario `root`?

**Comment by jonduttweiler** [comment]
Mauri, si la cambie porque no recordaba la anterior y no podia acceder a lo de los certificados, ya te la paso por whatsapp

**Comment by cmauriciocoronel** [comment]
Gracias Jona. CIerro el issue.
