### ISSUE TITLE
Construir imagen faltantes

### ISSUE THREAD

**Issue by cmauriciocoronel** [ACDI-Argentina/efem-crowdfunding-dapp#24]
Se requiere construir imágenes faltantes en la UI:

Landing page:

![image](https://user-images.githubusercontent.com/16942632/184516705-5a6df619-a551-44ce-972d-f25c18df4bb2.png)

![image](https://user-images.githubusercontent.com/16942632/184516711-c227cd8b-c438-4b39-bdbb-4bfb967d4d56.png)

![image](https://user-images.githubusercontent.com/16942632/184516720-f9659832-394a-46f7-825a-750f2e092fb1.png)

About us

![image](https://user-images.githubusercontent.com/16942632/184516731-c692e3cf-90b6-4296-b81b-07ddd92a0c55.png)

**Comment by lucueto** [comment]
Mauri, hice una propuesta y la volqué en Figma. Fijate y decime qué opinas
![image](https://user-images.githubusercontent.com/104791670/187277352-8d8d92fe-04c9-4e23-b69e-40c00e30482d.png)

**Comment by cmauriciocoronel** [comment]
Me gusta Lu, quedò muy linda.

Podes adjuntar una imagen con mayor resolución por favor así la incluyo en la aplicación? Esta aparece un poco pixelada.

**Comment by lucueto** [comment]
![COLABORACION](https://user-images.githubusercontent.com/104791670/187331633-c1a9ae1e-5635-4ea7-ae69-2e734d644a62.png)
![TECNOLOGÍA](https://user-images.githubusercontent.com/104791670/187331650-d5fa3499-be71-4f13-a975-6f3284bff7d4.png)
![TRANSPARENCIA-TRAZABILIDAD](https://user-images.githubusercontent.com/104791670/187331666-d015c478-d3cf-422a-83a2-c554f6cfc811.png)

**Comment by cmauriciocoronel** [comment]
Gracias @lucueto! Nececitaría la imagen de fondo separada también. No la puedo descargar tal cual requieren en el issue #27.

**Comment by lucueto** [comment]
![Frame 716](https://user-images.githubusercontent.com/104791670/187800136-3256d088-1cac-4e7e-9322-c1ca257b7bf1.png)

**Comment by lucueto** [comment]
Espero que sea suficiente, de otro modo deicme y la descargo con mayor calidad sin problemas

**Comment by cmauriciocoronel** [comment]
Gracias Lu.

Se impactó la imagen requerida en el mabiente de beta.

Quedaría pendiente la imagen de la página About Us para cerrar este requerimiento.

**Comment by lucueto** [comment]
![1](https://user-images.githubusercontent.com/104791670/188220532-c6c86e7f-6e2f-4faf-9ac8-f346862dba13.png)
![4 v](https://user-images.githubusercontent.com/104791670/188220541-0e85b4cc-9145-4c08-951c-05e3f4446742.png)
<img width="1080" alt="colaborar tecno@2x" src="https://user-images.githubusercontent.com/104791670/188220547-8c1294eb-f0d5-484e-9dfc-21b8c85475ed.png">
![granchaco](https://user-images.githubusercontent.com/104791670/188220561-411740ef-677e-4357-b79b-7b66543a2f88.png)

**Comment by lucueto** [comment]
![image](https://user-images.githubusercontent.com/104791670/188220624-178ea6ea-a276-4a10-90b2-835554b4fc98.png)

**Comment by cmauriciocoronel** [comment]
Se impactaron las imagenes. Se cierra el issue.
