### ISSUE TITLE
Actualizar items de FAQ

### ISSUE THREAD

**Issue by cmauriciocoronel** [ACDI-Argentina/efem-crowdfunding-dapp#26]
Se requiere actualizar las preguntas y respuesta de la FAQ.

![image](https://user-images.githubusercontent.com/16942632/185243373-09478e17-3a6f-48db-9792-f40916fb4c29.png)

Se necesitan las preguntas y respuestas reales de la plataforma.

**Comment by lucueto** [comment]
Hola Mauri, justo ayer las cargué, se ve que lo hicimos los dos, comentario y carga de info, al mismo tiempo.
Nos vemos hoy!

**Comment by Barostegui** [comment]
Hola @cmauriciocoronel te dejo el link con las preguntas. hay dos al final a completar, pero podemos ir volcando las otras
https://docs.google.com/document/d/1cSFu_2DUkuVcgtSxKchiMCbSN-u8Zo9ria-4jqCzOi8/edit

**Comment by cmauriciocoronel** [comment]
Se impactaron las FAQs documentadas, a excepción de las siguientes porque figuran como pendientes:

- ¿Cómo donar otras criptomonedas?
- ¿Qué sucede si no se alcanzan los fondos de un proyecto?

**Comment by lucueto** [comment]
A revisar en el diseño de la sección:
Mayúsculas y tamaños
Colores
Sistema y disposición de la información

La idea es que, si se puede, se tenga una vista general de las preguntas y tenga un link a la parte de la página en la que se encuentre la respuesta; pero que también exista la opción de que el usuario scrollee y revise todas las preeguntas y respuestas por sí mismo. 
Otra idea es que las preguntas se encuentren debajo del título, con la disposición que se propone en Figma, pero con la posibilidad de desplazar u ocultar las respuestas debajo de las preguntas. 

No sé si me explico bien, y si se puede. Pero esas serían las opciones y ajustes para aplicar en este caso.

**Comment by cmauriciocoronel** [comment]
Se realizó el cambio propuesto. Se muestra solo el listado de preguntas y el usuario puede expandir las respuestas.
