### ISSUE TITLE
Ajustes web

### ISSUE THREAD

**Issue by Barostegui** [ACDI-Argentina/efem-crowdfunding-dapp#27]
@cmauriciocoronel dejo acá los comentarios sobre el diseño de la web q vimos con Lucía. 

https://docs.google.com/presentation/d/1Un2ZSj_lUBKGThp3MEhYFCoA_a88HqV2I_Vp51xyahA/edit#slide=id.p

lo puse inicialmente en español, mañana lo agrego en inglés. avisame cualquier duda. 

fyi @lucueto

**Comment by cmauriciocoronel** [comment]
Se avanzó sobre lo solicitando.

En **negrita** se resaltan los puntos faltantes:

_Home_
- Página 3: Se hicieron ajustes sobre los espacios en blanco para mejorar el scrolling. No se puede realizar con exactitud sobre los puntos de corte requeridos.
- Página 4: Hecho.
- Página 5: Se configuró color sólido en el header.
- Página 6: Hecho.
- **Página 7:** No hice los cambios porque no puedo descargar de figma la imagen exacta que requieren. La adjuntarían al issue por favor? Esto está relacionado al Issue #24.
- Página 8: Hecho.
- Página 9: Hecho.

_About us_
- **Página 11:** Hecho. Falta foto.
- **Página 12:** Hecho. Falta foto.
- Página 13: Hecho.
- Página 14: Hecho.

_FAQs_
- Página 16: Hecho.

_Solución caso Kokue_
- Página 18: El proyecto solo puede tener una única red social al crearse, por lo que hay que elegir una al momento de darlo de alta. El botón de donar aparece cuando el usuario conecta la wallet.
- Página 19: No se hicieron cambios en la aplicación porque son cambios de cambios de contenido.
- Página 20: No se hicieron cambios en la aplicación porque son cambios de cambios de contenido.
- Página 21: Hecho. Falta la definción del abstract y monto del hito 3.

> Para no perder la trazababilidad del trabajo realizado con el documento, por favor realizar otra versión del doc si es necesaria cambiarlo o incluir en el mismo issue los cambios.

**Comment by cmauriciocoronel** [comment]
Se resolvió el punto pendiente en la **Página 7** por el trabajo de nota https://github.com/ACDI-Argentina/give-4-forest/issues/24#issuecomment-1233531644.

Quedan pendientes los puntos de las **Páginas 11** y **12**.

**Comment by cmauriciocoronel** [comment]
Se impactaron las imagenes faltantea de las **Páginas 11** y **12** en el issue #24. Se cierra el issue.
