### ISSUE TITLE
Imágenes para suplir en La revolución de la tecnología - About Us

### ISSUE THREAD

**Issue by lucueto** [ACDI-Argentina/efem-crowdfunding-dapp#28]
@cmauriciocoronel 
![image](https://user-images.githubusercontent.com/104791670/190868929-20cc3774-fc6f-4d2f-ae6b-8e3773c6515a.png)

![BLOCK-ESQUEMA](https://user-images.githubusercontent.com/104791670/190868898-88978611-10c0-4da9-9999-2f76eb16c52b.png)

**Comment by cmauriciocoronel** [comment]
Impactado por pedido de cambio de imagen de Issue #30, Página 6.
