### ISSUE TITLE
Sección Kokue 

### ISSUE THREAD

**Issue by lucueto** [ACDI-Argentina/efem-crowdfunding-dapp#29]
![1 A ](https://user-images.githubusercontent.com/104791670/191144349-06661827-9a6f-461b-9f6f-b9123138851a.jpeg)
![ACDI](https://user-images.githubusercontent.com/104791670/191144354-5b4a9538-7167-444d-a70f-5eb34637f63f.png)
![APP KOKUE](https://user-images.githubusercontent.com/104791670/191144357-15eaba3d-fde4-44ba-aec0-c94f871eed5c.png)
![Comunidad Wichí Vizcacheral_NicoHeredia (23)](https://user-images.githubusercontent.com/104791670/191144359-9a30c3ca-23e0-49e0-89ed-33d09894e4cb.jpg)
![EFEEEM](https://user-images.githubusercontent.com/104791670/191144363-e09da94a-122b-4341-b2b8-ea53b0590208.png)
![GRAL](https://user-images.githubusercontent.com/104791670/191144364-b8f27aa4-f648-439f-8980-afe4c8fd00e6.png)

Uploading KOKUE ZAYED -vf_2_1.mp4…

https://www.figma.com/file/oE8c6yR3Tx80qh10LzIPI1/G4f?node-id=238%3A276

**Comment by lucueto** [comment]
https://drive.google.com/drive/folders/1xQA7ptt6lpVulwdR21I5wrVA-iHrADYo?usp=sharing

Video KOKUE

**Comment by lucueto** [comment]
<img width="1046" alt="APP KOKUE@2x" src="https://user-images.githubusercontent.com/104791670/194429975-07b2b45b-5691-4a23-a1c6-bbe28ab33db6.png">
Nuevas imágenes para reemplazar fotos anteriores.
[
<img width="398" alt="1@2x" src="https://user-images.githubusercontent.com/104791670/194429903-5d45f96a-16b3-4fde-9085-60de1e31b7c4.png">
<img width="397" alt="2_1@2x" src="https://user-images.githubusercontent.com/104791670/194429913-2445942b-789c-4c02-a42e-00fde9feda99.png">
](url)

**Comment by lucueto** [comment]
<img width="921" alt="Mesa de trabajo 10@2x" src="https://user-images.githubusercontent.com/104791670/195375663-f8213b53-bed8-4564-b5b7-fc952e9fd0a6.png">
<img width="966" alt="Mesa de trabajo 11@2x" src="https://user-images.githubusercontent.com/104791670/195375668-8f7f7d64-fef9-4017-abc2-3aabc1d5a7d8.png">
![mac avaldao](https://user-images.githubusercontent.com/104791670/195375743-2c9802db-08f1-4680-9ede-d2a139d81c97.png)
<img width="145" alt="ACDI_1@2x" src="https://user-images.githubusercontent.com/104791670/195376093-ef388ef9-2602-4fb2-86d8-9fa6a4cd64c0.png">
<img width="145" alt="BIDLAB@2x" src="https://user-images.githubusercontent.com/104791670/195376102-45794801-6658-48a0-9379-232c816a36c9.png">
<img width="145" alt="EFEEEM_1@2x" src="https://user-images.githubusercontent.com/104791670/195376105-05a205a9-5769-427f-ba70-5ba18aabd920.png">
<img width="145" alt="IOVLABS@2x" src="https://user-images.githubusercontent.com/104791670/195376107-8fc7478b-642d-4608-b90a-063c5fab7b73.png">
<img width="145" alt="RSK@2x" src="https://user-images.githubusercontent.com/104791670/195376110-5f4b1468-bddb-47b4-bb0b-4f4ae27c366e.png">

**Comment by lucueto** [comment]
![kokue](https://user-images.githubusercontent.com/104791670/195716678-12fb5f12-dd5c-4b97-b619-811dae583372.png)

**Comment by lucueto** [comment]
![Logo-Kokue](https://user-images.githubusercontent.com/104791670/195717101-8f1437c2-17ba-48b2-8ec0-a60ef7e0f56c.png)
<img width="233" alt="kokue@2x" src="https://user-images.githubusercontent.com/104791670/195717116-2617bf1a-3228-4fab-895f-6d04114c0ab9.png">

**Comment by lucueto** [comment]
![kokue@3x](https://user-images.githubusercontent.com/104791670/195718797-59042cd1-3cfb-478a-a0d0-c799ff188e34.png)

**Comment by lucueto** [comment]
![kokue1](https://user-images.githubusercontent.com/104791670/195719064-144b1218-2705-471a-a057-0fcb8b6b647e.png)

**Comment by lucueto** [comment]
![kokue1](https://user-images.githubusercontent.com/104791670/195719679-21fb6181-0b55-4162-86c6-04d86d530953.png)

**Comment by cmauriciocoronel** [comment]
Esto lo ha impactado @Barostegui en Producción.
Cierro el issue.
