### ISSUE TITLE
ajustes home y sección about us

### ISSUE THREAD

**Issue by Barostegui** [ACDI-Argentina/efem-crowdfunding-dapp#30]
@cmauriciocoronel adjunto los ajustes a considerar en la migración del beta al online. 
De este ppt, tomar diapositivas de la 1 a la 7 inclusive. NO tomar de la 8 en adelante. 
https://docs.google.com/presentation/d/1Un2ZSj_lUBKGThp3MEhYFCoA_a88HqV2I_Vp51xyahA/edit#slide=id.g1514965c20a_0_3

**Comment by cmauriciocoronel** [comment]
Se avanzó hasta la página 7.

- Página 2: El header es fijo. Se disminuyó el alto de las tarjetas de proyectos para que se visualicen sin necesidad de scrollear. Querda pendiente actualizar el resumen del proyecto Kokue.
- Página 3: Hecho.
- Página 4: Hecho.
- Página 6: Hecho. Se tomó la imagen del issue https://github.com/ACDI-Argentina/give-4-forest/issues/28.
- Página 7: Hecho.

**Comment by cmauriciocoronel** [comment]
Estos ajustes ya se han realizado.
EL documento referencia ha cambiado, por lo que perdió el tracking de cambios.
