### ISSUE TITLE
Transferencia de Campaign Manager

### ISSUE THREAD

**Issue by Barostegui** [ACDI-Argentina/efem-crowdfunding-dapp#33]
Un campaign Manager se debe poder transferir, porque si un responsable de proyecto cambia de función debe poder asignar a otro, así como editar la campaña en caso no haya sido el creador. 

Avisar a Belén por @ cuando esté realizado dado que no llega notificación al mail sino.

**Comment by cmauriciocoronel** [comment]
Se incoporó la edición del Manager de Camapaña.

El mismo requirió de una cambio a nivel de smart contrat en la blockchain.
