### ISSUE TITLE
Sección "Solutions" / "Soluciones"

### ISSUE THREAD

**Issue by Barostegui** [ACDI-Argentina/efem-crowdfunding-dapp#36]
Así como está creada la sección "Create solutions" (https://give4forest.org/create-solutions)  debe haber una sección "Solutions" donde se puedan visualizar todas las campañas postulantes a recaudación de fondos. 

El botón "View Solutions" que se pega debajo debe derivar a esa sección, así como el botón del encabezado y pie "Solutions"

Esa seccion debe tener la posibilidad al igual que la home de filtrar por App / DApp / Accesibility

<img width="388" alt="image" src="https://user-images.githubusercontent.com/111588947/196464916-33d61830-b651-4acb-8bee-7ab6c5821710.png">

**Comment by cmauriciocoronel** [comment]
Se incorporó la sección solicitada.
