### ISSUE TITLE
URGENTE - ERROR URL Redireccionamiento

### ISSUE THREAD

**Issue by Barostegui** [ACDI-Argentina/efem-crowdfunding-dapp#39]
Las campañas permiten solo 1 URL. Dado que en su mayoría son Apps, debemos poner la URL al link de desgarga en google play. 
EJ, campaña KOKUE: https://play.google.com/store/apps/details?id=com.project.kokue&hl=es_AR&gl=US

Sin embargo, el espacio tiene una limitación de caracteres y solo deja poner hasta acá: 
https://play.google.com/store/apps/details 
llevando a un redireccionamiento incorrecto. No sirve con limitante de caracteres. 

Es necesario corregir que NO tenga limitacion de caracteres

**Comment by cmauriciocoronel** [comment]
Se extendió la capacidad desde 42 caracteres a 256 caracteres para la URL.

**Comment by Barostegui** [comment]
en AdApp, cuando quise cargar la url  https://play.google.com/store/apps/details?id=org.proadapt.granchaco.adapp&hl=es&gl=US solo me tomaba hasta ....apps/detail no me deja pegar links más largos
@cmauriciocoronel

**Comment by cmauriciocoronel** [comment]
Todavía no estaba impactado el cambio en Producción @Barostegui.

Ya se encuentra el arreglo disponible.
