### ISSUE TITLE
ajustes idioma inglés G4F

### ISSUE THREAD

**Issue by Barostegui** [ACDI-Argentina/efem-crowdfunding-dapp#40]
Mauricio, 
hemos hecho revisar el uso correcto del idioma del sitio y nos han pasado estos ajustes del idioma inglés que te pego en el documento siguiente. Por el momento está la sección HOME y ABOUT US. 
https://docs.google.com/presentation/d/17GnTOHQG9-YhozRtypdQWiFCScnPIjgoTav4fAbSHlY/edit#slide=id.g16ee1e499a2_0_105

Verás que marqué en rojo aquellas partes que solo es algún cambio menor de palabras y otras puse directo el párrafo completo. Avisame si hay algo que no se entiende. 

Cuando me pasen la revisión de cada campaña y del FAQS te lo comento acá mismo.

**Comment by cmauriciocoronel** [comment]
@Barostegui se solitó acceso al documento.

**Comment by Barostegui** [comment]
ahí te di acceso @cmauriciocoronel 
gracias

**Comment by cmauriciocoronel** [comment]
@Barostegui hecho.

**Comment by Barostegui** [comment]
gracias! 
te paso 2 puntos que quedaron faltaron: @cmauriciocoronel 

Acá debe decir innovations (falta una N)
<img width="397" alt="Captura de Pantalla 2022-10-21 a la(s) 14 34 23" src="https://user-images.githubusercontent.com/111588947/197255692-0edb343b-0c5c-43e0-bd01-9190ae1efe77.png">

acá faltó borrar el THE
<img width="985" alt="Captura de Pantalla 2022-10-21 a la(s) 14 37 29" src="https://user-images.githubusercontent.com/111588947/197256958-a197b6e3-f67c-4c04-b9be-17acdb767690.png">

solo eso gracias

**Comment by cmauriciocoronel** [comment]
@Barostegui se impactaron las 2 correcciones y estarán disponibles en la próxima versión.
