### ISSUE TITLE
URGENTE error ajuste campaña AdApp

### ISSUE THREAD

**Issue by Barostegui** [ACDI-Argentina/efem-crowdfunding-dapp#41]
Mauricio desde ayer que no puedo editar la campaña de Adapp. 
ya he reiniciado computadora, cerrado todos los programas pero por algún motivo no me deja editar. No me aparece directamente la confirmación de la billetera. 
me podrás indicar si surge algún otro problema que vos estés pudiendo identificar?

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/111588947/196796287-d652f0bc-24a2-49f8-b5bf-8f6bd051cae8.png">

<img width="674" alt="image" src="https://user-images.githubusercontent.com/111588947/196796343-e6d7eafc-9872-4f8d-9abb-4038e06a2de3.png">

**Comment by cmauriciocoronel** [comment]
@Barostegui esto puede deberse a que la campaña no fue confirmada aún en la blockchain como dice el popup.

Por favor, volvé a intentar editar una vez más y cualquier cosa lo vemos. Debería funcionar.

**Comment by Barostegui** [comment]
@cmauriciocoronel volví a intentarlo luego de un rato y ayer lo intenté varias veces en diferentes momentos, al igual que hoy. hay alguna falla que no logro identificar porque no salen más carteles que los que mostré. No aparece nunca la visualización de la wallet para confirmar. 
Intente con otra campaña (avaldao) y ahi si funciona, solo en Adapp no me deja subir o cambiar contenido.

**Comment by Barostegui** [comment]
ahí fui subiendo de a item por item los contenidos e identifiqué que no permite subir foto. le bajé peso de 2,3mb a 700kb y ninguna permite. adjunto las dos imágenes para que me indiques qué puede ser @cmauriciocoronel 
gracias

![Adappterreno1](https://user-images.githubusercontent.com/111588947/197033134-504b85bc-df47-45e6-aa08-0cd3b9186b1d.jpg)
![AdApp](https://user-images.githubusercontent.com/111588947/197033190-0ee9364d-efe4-4828-9d05-9a7125d19a75.jpg)

**Comment by cmauriciocoronel** [comment]
@Barostegui pude subir la imagen sin problemas.

La reduje a 260KB antes de subirla. La adjunto acá para que se pueda modificar si es requerido.

![197033190-0ee9364d-efe4-4828-9d05-9a7125d19a75](https://user-images.githubusercontent.com/16942632/197076370-7a3608f6-1099-414e-a028-082cb3b6def4.jpg)
