### ISSUE TITLE
Tags en G4F para trackeo de visitas al sitio

### ISSUE THREAD

**Issue by Barostegui** [ACDI-Argentina/efem-crowdfunding-dapp#42]
@cmauriciocoronel  por favor pegar el siguiente código de este tag manager https://drive.google.com/drive/folders/1hC1nTp5JaxR0oIDv3PcRsGpCw4Na-sCM en el sitio. 

Consulta, me indica quien está haciendo el SEO del sitio que ya hay un google analytics pegado, puede ser?
Lo gestionaste vos?
Podés darme a mi y a micaela@bper.digital acceso de administradora? es para actualizarlo al GA4 y armar las configuraciones.

gracias

**Comment by Barostegui** [comment]
Hola @cmauriciocoronel 
mañana lanzamos la plataforma y necesito por favor esté puesto este código. De no estar, no tengo posibilidad de identificar si empieza a haber tráfico en el sitio o no, por lo que te pido si podés darle prioridad a este tema de los que hay. 
gracias

**Comment by Barostegui** [comment]
@cmauriciocoronel por favor necesito se aplique este código al sitio. 
fyi @mmorescoACDI

**Comment by cmauriciocoronel** [comment]
@Barostegui te solicité permisos sobre el documento.

Desconozco si tiene configurado otro Google Analytics. Quizás trae uno del anterior proyecto.

**Comment by Barostegui** [comment]
Ya estan dados los permisos @cmauriciocoronel

**Comment by cmauriciocoronel** [comment]
Se agregó el ID de trackeo solicitado a la librería de React.

**Comment by Barostegui** [comment]
figura como si hubiera pegado el pixel diciendo que es de Analytics pero código enviado es de Google tag manager. Y tampoco se ve en el código fuente. Pego los prints de pantalla con los errores que aparecen. 
Hay unos links instructivos en el archivo del pixel compartido. Un código hay que pegarlo en el head y el otro codigo en el body. Igualmente te dejo más info en este [[link](https://support.google.com/tagmanager/?hl=es#topic=3441530)] por si le surgen dudas. 
En el caso que no sepas como hacerlo, te pido acceso al sitio web a esta persona micaela@bper.digital o un acceso abierto para que desde la agencia lo puedan pegar. 

<img width="1440" alt="Captura de Pantalla 2022-11-07 a la(s) 11 21 29" src="https://user-images.githubusercontent.com/111588947/200339408-256810f8-19a7-4663-8d0f-004afd0b9a39.png">
<img width="1440" alt="Captura de Pantalla 2022-11-07 a la(s) 11 21 37" src="https://user-images.githubusercontent.com/111588947/200339466-697d67e2-09cd-4a01-ad76-3300eebccd8e.png">

**Comment by cmauriciocoronel** [comment]
@Barostegui, se incorporó GTM a la aplicación de acuerdo a las instrucciones y se deshabilitó GA que ya existía desde antes.

![image](https://user-images.githubusercontent.com/16942632/200450175-e768ffe8-c917-4e4a-8f78-7f250ae22e66.png)

Algunas consideraciones:

- La aplicación es una SPA desarrollada en React, por lo que la misma cuenta con una única página y el tracking de los distintos path no se puede realizar con la técnica indicada. Habría que investigar qué librerías de React están disponibles actualmente para GTM.
- Se modificó el archivo index.html con las instrucciones indicadas, por lo que se estarán enviando métricas de acceso al ambiente Beta también. Queda pendiente investigar qué mecanimos de customización de este archivo puede hacerse por ambiente.

En cuanto a dar acceso de adminitración, G4F es open source por lo que cualquiera puede contribuir. Aquí están los fuentes del proyecto: https://github.com/ACDI-Argentina/give-4-forest
