### ISSUE TITLE
Instructivo de Alta Users G4F

### ISSUE THREAD

**Issue by Barostegui** [ACDI-Argentina/efem-crowdfunding-dapp#43]
Consulto, existe un instructivo de cómo dar de alta Users en esta parte? https://give4forest.org/users 

así puedo dar de alta a MM como reviewer y cuando las líderes de proyecto tengan su billetera darlas de alta. 
así como también darme de alta a mi como perfil. 

@cmauriciocoronel 
graicas

**Comment by cmauriciocoronel** [comment]
@Barostegui no hay instructivo de cómo hacerlo en G4F, pero sí hay videos de cómo hacerlo en Avaldao, donde el procedimiento es el mismo:

https://github.com/ACDI-Argentina/avaldao/wiki/Videos#registraci%C3%B3n-de-usuario
https://github.com/ACDI-Argentina/avaldao/wiki/Videos#administraci%C3%B3n-de-usuario

Como lo he dicho en las demostraciones, cada usuario se da de alta por si mismo porque requiere de su wallet. Luego una admnitrador otorga los permisos necesarios para cada usuario. Esto se muestra en los videos.
