### ISSUE TITLE
Corrección About US

### ISSUE THREAD

**Issue by Barostegui** [ACDI-Argentina/efem-crowdfunding-dapp#50]
@cmauriciocoronel 
acá debe aparecer el apellido de Mauricio : Mauricio Moresco (no la M.)
gracias

<img width="359" alt="image" src="https://user-images.githubusercontent.com/111588947/199591324-3e59884e-1521-415d-9e0a-cf2456d636ea.png">

**Comment by cmauriciocoronel** [comment]
Hecho.
