### ISSUE TITLE
Registro de mail para recibir PODs por donación

### ISSUE THREAD

**Issue by Barostegui** [ACDI-Argentina/efem-crowdfunding-dapp#51]
@cmauriciocoronel 
Hemos avanzado con la propuesta de enviar Proof of Donations (PODs) a quienes hagan donaciones, tal como tuvimos la reunión hace un tiempito. Para ello precisamos informar, pedir y facilitar el acceso para que registren su mail en su perfil al momento de donar. Te pido los siguientes cambios a hacer en el proceso de querer donar: 

<img width="913" alt="Captura de pantalla 2023-03-14 a la(s) 17 14 32" src="https://user-images.githubusercontent.com/111588947/225130768-53d8e03a-db13-47ff-8323-bc8826695d6b.png">

CAMBIOS: 
Donate to campaign / Donar a campaña : reemplazar por Donate to solution / español: Donar a solución

Txt dentro del cuadro, reemplazar x: 
INGLES: 
You are committing your funds to this solution. Fill out your email in your profile and you will get a Proof of Donation NFT and also be notified about how your funds are spent.

ESPAÑOL:
Estás comprometiendo tus fondos para esta solución. Completá tu mail en tu perfil y recibirás una Prueba de Donación NFT, así como notificaciones de cómo se gastan tus fondos.

Debemos agregar un botón que diga “GO TO PROFILE” / “IR A PERFIL” que redireccione a la sección para completar el mail en el perfil.

<img width="1002" alt="Captura de pantalla 2023-03-14 a la(s) 11 49 10" src="https://user-images.githubusercontent.com/111588947/225131157-7a415f01-556c-4825-896b-0417745aef88.png">

Una vez dentro del perfil, el campo de URL, podría NO ser obligatorio? porque las personas no van a tener una URL necesariamente. 

Una vez que Donaron, no se qué cartel aparece. Hay forma de verlo? 
En la instancia post donación, también debería haber un botón a ir a PERFIL en caso que no haya registrado antes el mail, para que pueda hacerlo posterior, así como la mención del POD a recibir. 

Por último, preciso saber cómo accedo a los mails que se van registrando. 

Por favor cualquier duda consultame. Gracias.

**Comment by cmauriciocoronel** [comment]
Se realizaron los siguientes cambios en _Beta_ y _Producción_ según lo requerido:

1. Se cambió el título de la donación.
2. Se cambió la descripción de la donación.
3. No se agregó un nuevo botón de _Ir a perfil_ porque ya existe en el menú del usuario, denominado _Perfil_.
4. Se configuró como opcional la _URL_ del perfil del usuario.

Una vez que la donación finaliza, aparece el siguiente popup y puede modificarse:

![image](https://user-images.githubusercontent.com/16942632/227742477-efd7b67d-a4b7-49f9-af13-fc7ba075a1e5.png)

Los mails que se van registrando se pueden ver con la cuenta de administración de usuarios a través de la misma aplicación.

**Comment by Barostegui** [comment]
Gracias @cmauriciocoronel 
en el pop up que aparece al finalizar la donación, te pido modificar al siguiente texto: 

INGLES:
The donation has been confirmed. 
Thank you very much for your commitment! Remember to fill out your email in your profile to receive your Proof of Donation NFT.

ESPAÑOL:
Tu donación ha sido confirmada. 
Muchas gracias por tu compromiso! Recordá completar tu mail en tu perfil  para recibir tu NFT Prueba de Donación.

**Comment by cmauriciocoronel** [comment]
@Barostegui los cambios solicitados fueron impactados en _Beta_ y _Producción_.
