### ISSUE TITLE
Mención en Web de entrega de PODs

### ISSUE THREAD

**Issue by Barostegui** [ACDI-Argentina/efem-crowdfunding-dapp#52]
@lucueto vamos a estar haciendo entrega de NFTs Proof of Donations para aquellos que donen en G4F. Esto queremos mencionarlo en la página. 
Lo agregaría en We build community. Sin alargar ese espacio, agregaría un 4to elemento, que sea 
Proof of Donation // ESP: Pruebas de donación
que diga: Donors receive a certification of donations made and initiatives supported, building a reputation based on impact.
// ESP: Los donantes reciben una certificación de las donaciones realizadas e iniciativas apoyadas, creando una reputación basada en la generación de impacto. 

lo copio a @cmauriciocoronel para que una vez diseñado, lo implemente en la pág. 

<img width="479" alt="Captura de pantalla 2023-03-14 a la(s) 18 27 33" src="https://user-images.githubusercontent.com/111588947/225150422-244e3559-2c44-400a-a90d-ff1763273576.png">

**Comment by lucueto** [comment]
![TRANSPARENCIA-TRAZABILIDAD copia1](https://user-images.githubusercontent.com/104791670/229887680-07be1d93-86e3-47bb-bd30-2d76ea754b08.png)
![TRANSPARENCIA-TRAZABILIDAD1](https://user-images.githubusercontent.com/104791670/229887688-28c3631e-d8cd-4af0-9f8c-4b320ecfcfe0.png)
![TRANSPARENCIA-TRAZABILIDAD21](https://user-images.githubusercontent.com/104791670/229887694-cb5cd89e-d423-4570-be21-13c9c56b9a1d.png)

Dejo los archivos, son dos opciones para la Certificación. Una más horizontal y otra más cuadrada, porque no sé bien cómo van los espacios.
También dejo otra imagen para Transparencia y Trazabilidad, para cambiar la que hay. Repasé los diseños de redes que me habían pasado, y ví que la imagen correspondiente era la que apliqué ahora, la anterior la habían usado para certificación.

**Comment by lucueto** [comment]
Dejo los archivos, son dos opciones para la Certificación. Una más horizontal y otra más cuadrada, porque no sé bien cómo van los espacios.
También dejo otra imagen para Transparencia y Trazabilidad, para cambiar la que hay. Repasé los diseños de redes que me habían pasado, y ví que la imagen correspondiente era la que apliqué ahora, la anterior la habían usado para certificación.
![TRANSPARENCIA-TRAZABILIDAD1](https://user-images.githubusercontent.com/104791670/229891682-5cef656c-c874-42fc-b38d-abc4524e0213.png)

![Uploading Desktop.png…]()


![CERTIFICATION](https://user-images.githubusercontent.com/104791670/229891664-3936d510-6690-42e2-aac8-4f8339617456.png)
![CERTIFICATION2](https://user-images.githubusercontent.com/104791670/229891674-24982121-2f9d-473a-919f-d525c5015ebb.png)

**Comment by Barostegui** [comment]
Hola @lucueto perdón no comprendí. proponés hacer un cambio de todas las imágenes? las que están para Collaboration, Technology y Transparency yo las veo bien, no las cambiaría. 
Lo que hacemos ahora es entregar un NFT colleccionable que es una prueba de donación, que se le envía a la billetera al donante. Ese NFT va cambiando esporádicamente, ahora tenemos 1 puntual que es de Lanzamiento, por tal motivo no digo de ponerlo como ejemplo porque va a ir cambiando/ampliándose. Pero si debemos poner una imagen que represente que van a recibir ese NFT como prueba de su donación. 
Pego el NFT de lanzamiento para que veas qué le llega. 
Avisame si se comprende.

![POD_G4F](https://user-images.githubusercontent.com/111588947/229963725-a058d66a-6119-4e95-be6b-b73ab951d0fa.gif)

**Comment by lucueto** [comment]
Paso otra prueba! 

![PROOF DONATION-21](https://user-images.githubusercontent.com/104791670/230461115-b038cc3e-dc16-4c5a-9cd4-bfe8172c3e62.png)

**Comment by Barostegui** [comment]
Hola @lucueto , va por este camino, pero representaría los pasos 
Donante - criptomoneda - solución
Impacto - NFT - Donante

Las imágenes que usaste me parecen genial, con Impacto refiero a las imágenes que usaste del entorno natural+fauna, esas las dejaría. solo que representaría todo el circuito si es posible.

**Comment by lucueto** [comment]
![PROOF DONATION-31](https://user-images.githubusercontent.com/104791670/231019635-7672016f-f043-4d75-8292-ff503dfdc806.png)

Dejo una idea... Me da miedo por ahí que la idea de circuito quede medio reiterativa, porque ya la usamos también en Transparencia...

**Comment by Barostegui** [comment]
gracias Lu. si, pero para esta instancia estamos ok así avanzamos.
@cmauriciocoronel por favor entonces si podés tomar esta imagen y colocarla en la home, respetando el izq-der-izq-der de ubicación de imagen/txt en el área. 
gracias!

**Comment by Barostegui** [comment]
Hola @cmauriciocoronel me avisás si podés hacer esta implementación en los proximos días por favor?
necesitamos comunicarlo
gracias!

**Comment by cmauriciocoronel** [comment]
El cambio se ha impactado en G4F de _Testing_ y _Producción_.
